// Mock data for standalone frontend development
// No backend required when REACT_APP_MOCK_MODE=true

export const mockUser = {
  id: 1,
  name: "Naren Dev",
  email: "naren@cnio.dev",
  imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=naren",
  isSubscribed: true,
  roles: ["ROLE_USER"],
  phone: "+91 8072205480",
  createdAt: "2024-06-15T10:00:00Z",
};

export const mockMovies = [
  {
    tmdbId: 550,
    id: 550,
    title: "Fight Club",
    description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    year: 1999,
    poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QI4S2t0POoT.jpg",
    ageRating: "R",
    rating: 8.4,
    vote_average: 8.4,
    voteCount: 27500,
    popularity: 61.5,
    runtime: 139,
    genre: "Drama",
    trailer: "https://www.youtube.com/watch?v=SUXWAEX2jlg",
    cost: 0,
  },
  {
    tmdbId: 27205,
    id: 27205,
    title: "Inception",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    year: 2010,
    poster: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEhniJIssEIY.jpg",
    ageRating: "PG-13",
    rating: 8.8,
    vote_average: 8.8,
    voteCount: 34000,
    popularity: 82.3,
    runtime: 148,
    genre: "Sci-Fi",
    trailer: "https://www.youtube.com/watch?v=YoHD9XEInc0",
    cost: 0,
  },
  {
    tmdbId: 238,
    id: 238,
    title: "The Godfather",
    description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    year: 1972,
    poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    ageRating: "R",
    rating: 9.2,
    vote_average: 9.2,
    voteCount: 19000,
    popularity: 95.1,
    runtime: 175,
    genre: "Crime",
    trailer: "https://www.youtube.com/watch?v=UaVTIH8mujA",
    cost: 0,
  },
  {
    tmdbId: 244786,
    id: 244786,
    title: "Whiplash",
    description: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    year: 2014,
    poster: "https://image.tmdb.org/t/p/w500/7fn624j544nwdf1DzMdCnLz7Luv.jpg",
    ageRating: "R",
    rating: 8.5,
    vote_average: 8.5,
    voteCount: 15000,
    popularity: 42.8,
    runtime: 106,
    genre: "Drama",
    trailer: "https://www.youtube.com/watch?v=7d_jQycdQGo",
    cost: 0,
  },
  {
    tmdbId: 155,
    id: 155,
    title: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    year: 2008,
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    ageRating: "PG-13",
    rating: 9.0,
    vote_average: 9.0,
    voteCount: 30000,
    popularity: 78.4,
    runtime: 152,
    genre: "Action",
    trailer: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    cost: 0,
  },
  {
    tmdbId: 680,
    id: 680,
    title: "Pulp Fiction",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    year: 1994,
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    ageRating: "R",
    rating: 8.9,
    vote_average: 8.9,
    voteCount: 25000,
    popularity: 55.2,
    runtime: 154,
    genre: "Crime",
    trailer: "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
    cost: 0,
  },
  {
    tmdbId: 13,
    id: 13,
    title: "Forrest Gump",
    description: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
    year: 1994,
    poster: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    ageRating: "PG-13",
    rating: 8.8,
    vote_average: 8.8,
    voteCount: 24000,
    popularity: 60.7,
    runtime: 142,
    genre: "Drama",
    trailer: "https://www.youtube.com/watch?v=bLvqoHBptjE",
    cost: 0,
  },
  {
    tmdbId: 278,
    id: 278,
    title: "The Shawshank Redemption",
    description: "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison.",
    year: 1994,
    poster: "https://image.tmdb.org/t/p/w500/9cjIGRiQoRCgTNEMmcoADji7lMv.jpg",
    ageRating: "R",
    rating: 9.3,
    vote_average: 9.3,
    voteCount: 24500,
    popularity: 98.5,
    runtime: 142,
    genre: "Drama",
    trailer: "https://www.youtube.com/watch?v/PLl99DlL6b4",
    cost: 0,
  },
  {
    tmdbId: 424,
    id: 424,
    title: "Schindler's List",
    description: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
    year: 1993,
    poster: "https://image.tmdb.org/t/p/w500/sF1DG4bBiY4577Fip4ey4lCj9dn.jpg",
    ageRating: "R",
    rating: 9.0,
    vote_average: 9.0,
    voteCount: 14500,
    popularity: 48.3,
    runtime: 195,
    genre: "Drama",
    trailer: "https://www.youtube.com/watch?v=gG22XJhCzUw",
    cost: 0,
  },
  {
    tmdbId: 240,
    id: 240,
    title: "The Godfather Part II",
    description: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
    year: 1974,
    poster: "https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    ageRating: "R",
    rating: 9.0,
    vote_average: 9.0,
    voteCount: 11200,
    popularity: 40.6,
    runtime: 202,
    genre: "Crime",
    trailer: "https://www.youtube.com/watch?v=9O1m9kdV4DE",
    cost: 0,
  },
  {
    tmdbId: 120,
    id: 120,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    description: "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator.",
    year: 2001,
    poster: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIYvG7CWRcGcfG.jpg",
    ageRating: "PG-13",
    rating: 8.8,
    vote_average: 8.8,
    voteCount: 23000,
    popularity: 72.1,
    runtime: 178,
    genre: "Fantasy",
    trailer: "https://www.youtube.com/watch?v=V757T0nX0PU",
    cost: 0,
  },
  {
    tmdbId: 19404,
    id: 19404,
    title: "Dilwale Dulhania Le Jayenge",
    description: "A young man and woman of Indian origin, both raised in London, fall in love during a trip across Europe.",
    year: 1995,
    poster: "https://image.tmdb.org/t/p/w500/2CAL23Z2aNb6T6dC4NxmmI2nFb.jpg",
    ageRating: "U",
    rating: 8.6,
    vote_average: 8.6,
    voteCount: 3800,
    popularity: 35.2,
    runtime: 190,
    genre: "Romance",
    trailer: "https://www.youtube.com/watch?v=MhICfMhJmYg",
    cost: 0,
  },
  {
    tmdbId: 598,
    id: 598,
    title: "City of God",
    description: "In the poverty-stricken favelas of Rio de Janeiro in the 1970s, two young boys choose very different paths in life.",
    year: 2002,
    poster: "https://image.tmdb.org/t/p/w500/k7eYdUvhYkI9oS8ejKmSjMw3sNn.jpg",
    ageRating: "R",
    rating: 8.7,
    vote_average: 8.7,
    voteCount: 8500,
    popularity: 38.9,
    runtime: 130,
    genre: "Crime",
    trailer: "https://www.youtube.com/watch?v=MkYJz1wDFsY",
    cost: 0,
  },
  {
    tmdbId: 769,
    id: 769,
    title: "GoodFellas",
    description: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.",
    year: 1990,
    poster: "https://image.tmdb.org/t/p/w500/aKuFiU82bpxb2KsAK4Un2PGheh6.jpg",
    ageRating: "R",
    rating: 8.7,
    vote_average: 8.7,
    voteCount: 11500,
    popularity: 37.4,
    runtime: 145,
    genre: "Crime",
    trailer: "https://www.youtube.com/watch?v=2ilzN3WmJac",
    cost: 0,
  },
  {
    tmdbId: 122,
    id: 122,
    title: "The Lord of the Rings: The Return of the King",
    description: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    year: 2003,
    poster: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    ageRating: "PG-13",
    rating: 9.0,
    vote_average: 9.0,
    voteCount: 22000,
    popularity: 68.9,
    runtime: 201,
    genre: "Fantasy",
    trailer: "https://www.youtube.com/watch?v=r5XtsF5uGQI",
    cost: 0,
  },
];

export const mockShows = [
  {
    tmdbId: 1396,
    id: 1396,
    name: "Breaking Bad",
    title: "Breaking Bad",
    description: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
    year: 2008,
    poster: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    ageRating: "TV-MA",
    rating: 9.5,
    vote_average: 9.5,
    voteCount: 13500,
    popularity: 85.3,
    runtime: 49,
    genre: "Drama",
    trailer: "https://www.youtube.com/watch?v=HhesaQXuU_Y",
    first_air_date: "2008-01-20",
    seasons: 5,
  },
  {
    tmdbId: 1399,
    id: 1399,
    name: "Game of Thrones",
    title: "Game of Thrones",
    description: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
    year: 2011,
    poster: "https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    ageRating: "TV-MA",
    rating: 8.4,
    vote_average: 8.4,
    voteCount: 22000,
    popularity: 90.2,
    runtime: 60,
    genre: "Fantasy",
    trailer: "https://www.youtube.com/watch?v=KPLWpGyaQCg",
    first_air_date: "2011-04-17",
    seasons: 8,
  },
  {
    tmdbId: 66732,
    id: 66732,
    name: "Stranger Things",
    title: "Stranger Things",
    description: "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
    year: 2016,
    poster: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    ageRating: "TV-14",
    rating: 8.7,
    vote_average: 8.7,
    voteCount: 17500,
    popularity: 72.8,
    runtime: 51,
    genre: "Sci-Fi",
    trailer: "https://www.youtube.com/watch?v=b9EkMc79ZSU",
    first_air_date: "2016-07-15",
    seasons: 4,
  },
  {
    tmdbId: 82856,
    id: 82856,
    name: "The Mandalorian",
    title: "The Mandalorian",
    description: "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
    year: 2019,
    poster: "https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
    ageRating: "TV-14",
    rating: 8.6,
    vote_average: 8.6,
    voteCount: 9800,
    popularity: 55.4,
    runtime: 40,
    genre: "Sci-Fi",
    trailer: "https://www.youtube.com/watch?v=aOC8ENS9bM8",
    first_air_date: "2019-11-12",
    seasons: 3,
  },
  {
    tmdbId: 94997,
    id: 94997,
    name: "Squid Game",
    title: "Squid Game",
    description: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes.",
    year: 2021,
    poster: "https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    ageRating: "TV-MA",
    rating: 8.0,
    vote_average: 8.0,
    voteCount: 15000,
    popularity: 92.1,
    runtime: 54,
    genre: "Thriller",
    trailer: "https://www.youtube.com/watch?v=oqxAJKy0ii4",
    first_air_date: "2021-09-17",
    seasons: 2,
  },
  {
    tmdbId: 71712,
    id: 71712,
    name: "The Witcher",
    title: "The Witcher",
    description: "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
    year: 2019,
    poster: "https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg",
    ageRating: "TV-MA",
    rating: 8.2,
    vote_average: 8.2,
    voteCount: 9200,
    popularity: 60.5,
    runtime: 60,
    genre: "Fantasy",
    trailer: "https://www.youtube.com/watch?v=ndl1W4ltcmg",
    first_air_date: "2019-12-20",
    seasons: 3,
  },
  {
    tmdbId: 60735,
    id: 60735,
    name: "The Flash",
    title: "The Flash",
    description: "After being struck by lightning, Barry Allen wakes up from his coma to discover he's been given the power of super speed.",
    year: 2014,
    poster: "https://image.tmdb.org/t/p/w500/lJA2RCMfsWoskqlQhXPSLFQGXEJ.jpg",
    ageRating: "TV-14",
    rating: 7.8,
    vote_average: 7.8,
    voteCount: 11200,
    popularity: 50.3,
    runtime: 45,
    genre: "Action",
    trailer: "https://www.youtube.com/watch?v=YxWHYiEzCMc",
    first_air_date: "2014-10-07",
    seasons: 9,
  },
  {
    tmdbId: 63174,
    id: 63174,
    name: "Lucifer",
    title: "Lucifer",
    description: "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles.",
    year: 2016,
    poster: "https://image.tmdb.org/t/p/w500/4EYPN5mVIhKLfxGruy7IJyWDsR.jpg",
    ageRating: "TV-14",
    rating: 8.5,
    vote_average: 8.5,
    voteCount: 14000,
    popularity: 62.7,
    runtime: 45,
    genre: "Crime",
    trailer: "https://www.youtube.com/watch?v=X2YPfJfDzS4",
    first_air_date: "2016-01-25",
    seasons: 6,
  },
  {
    tmdbId: 93405,
    id: 93405,
    name: "Squid Game: The Challenge",
    title: "Squid Game: The Challenge",
    description: "456 real players enter a competition inspired by the Squid Game series for a life-changing $4.56 million prize.",
    year: 2023,
    poster: "https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    ageRating: "TV-14",
    rating: 5.5,
    vote_average: 5.5,
    voteCount: 2200,
    popularity: 30.1,
    runtime: 45,
    genre: "Reality",
    trailer: "https://www.youtube.com/watch?v=oqxAJKy0ii4",
    first_air_date: "2023-11-22",
    seasons: 1,
  },
  {
    tmdbId: 84958,
    id: 84958,
    name: "Loki",
    title: "Loki",
    description: "After stealing the Tesseract during the events of Avengers: Endgame, Loki is brought to the mysterious Time Variance Authority.",
    year: 2021,
    poster: "https://image.tmdb.org/t/p/w500/voHUmluYmKyleFkTu3lOXQGCw6M.jpg",
    ageRating: "TV-14",
    rating: 8.2,
    vote_average: 8.2,
    voteCount: 10500,
    popularity: 58.9,
    runtime: 50,
    genre: "Sci-Fi",
    trailer: "https://www.youtube.com/watch?v=nW948Vaugkg",
    first_air_date: "2021-06-09",
    seasons: 2,
  },
  {
    tmdbId: 100088,
    id: 100088,
    name: "The Last of Us",
    title: "The Last of Us",
    description: "Twenty years after modern civilization has been destroyed, Joel is hired to smuggle Ellie out of an oppressive quarantine zone.",
    year: 2023,
    poster: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    ageRating: "TV-MA",
    rating: 8.8,
    vote_average: 8.8,
    voteCount: 7500,
    popularity: 75.4,
    runtime: 60,
    genre: "Drama",
    trailer: "https://www.youtube.com/watch?v=uLtptA4r4M0",
    first_air_date: "2023-01-15",
    seasons: 2,
  },
  {
    tmdbId: 124364,
    id: 124364,
    name: "Wednesday",
    title: "Wednesday",
    description: "Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends at Nevermore Academy.",
    year: 2022,
    poster: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    ageRating: "TV-14",
    rating: 8.1,
    vote_average: 8.1,
    voteCount: 8900,
    popularity: 68.2,
    runtime: 45,
    genre: "Comedy",
    trailer: "https://www.youtube.com/watch?v=Di310WS8zLk",
    first_air_date: "2022-11-23",
    seasons: 2,
  },
];

export const mockSouthIndianMovies = [
  {
    tmdbId: 545609,
    id: 545609,
    title: "RRR",
    description: "A fictional story about two legendary Indian revolutionaries and their journey away from joining forces.",
    year: 2022,
    poster: "https://image.tmdb.org/t/p/w500/kI7L0O9MSJdGO1r0HnPq7JkRKH.jpg",
    ageRating: "NR",
    rating: 7.9,
    vote_average: 7.9,
    voteCount: 3200,
    popularity: 55.8,
    runtime: 187,
    genre: "Action",
    trailer: "https://www.youtube.com/watch?v=f_vbAtFSEc0",
    cost: 0,
  },
  {
    tmdbId: 438148,
    id: 438148,
    title: "Baahubali 2: The Conclusion",
    description: "When Shiva learns about his heritage, he begins to bring down his uncle's reign, aided by the mighty warrior Kalakeya.",
    year: 2017,
    poster: "https://image.tmdb.org/t/p/w500/x3EbFPlvPfMg8M3H7E7FnJmGCw.jpg",
    ageRating: "NR",
    rating: 8.2,
    vote_average: 8.2,
    voteCount: 1800,
    popularity: 42.3,
    runtime: 167,
    genre: "Action",
    trailer: "https://www.youtube.com/watch?v=GiG0xnJ10sM",
    cost: 0,
  },
  {
    tmdbId: 653346,
    id: 653346,
    title: "Vikram",
    description: "A special Investigator is assigned to uncover the mystery behind a string of unusual murders in the city.",
    year: 2022,
    poster: "https://image.tmdb.org/t/p/w500/xG7dGj8p0uS3W4U2R1Fa6Mv6a6.jpg",
    ageRating: "NR",
    rating: 7.5,
    vote_average: 7.5,
    voteCount: 1200,
    popularity: 38.9,
    runtime: 157,
    genre: "Action",
    trailer: "https://www.youtube.com/watch?v=YSvxV4gKm0w",
    cost: 0,
  },
  {
    tmdbId: 87827,
    id: 87827,
    title: "K.G.F: Chapter 2",
    description: "In the blood-soaked Kolar Gold Fields, Rocky's name strikes fear into his foes. While the gangs plot against him, the government sends a formidable officer to end his reign.",
    year: 2022,
    poster: "https://image.tmdb.org/t/p/w500/2V0g2mUPJlVqY9Y91Xfnfg7EPQZ.jpg",
    ageRating: "NR",
    rating: 7.8,
    vote_average: 7.8,
    voteCount: 900,
    popularity: 35.6,
    runtime: 168,
    genre: "Action",
    trailer: "https://www.youtube.com/watch?v=JKP1w1cBzGI",
    cost: 0,
  },
  {
    tmdbId: 760741,
    id: 760741,
    title: "Beast",
    description: "An Indian army officer on a mission to rescue hostages from a hijacked plane.",
    year: 2022,
    poster: "https://image.tmdb.org/t/p/w500/kPvnC0YVz1K25Cyr13i4JH1QXiZ.jpg",
    ageRating: "NR",
    rating: 6.8,
    vote_average: 6.8,
    voteCount: 650,
    popularity: 28.4,
    runtime: 156,
    genre: "Action",
    trailer: "https://www.youtube.com/watch?v=24MXpMpQ4Ys",
    cost: 0,
  },
  {
    tmdbId: 981069,
    id: 981069,
    title: "Ponniyin Selvan: Part I",
    description: "A prince travels to rescue a kidnapped woman and encounters a mysterious warrior who holds the key to an ancient treasure.",
    year: 2022,
    poster: "https://image.tmdb.org/t/p/w500/tYj5tYFvQRQLQ3Jk3G13pGm6NpT.jpg",
    ageRating: "NR",
    rating: 7.2,
    vote_average: 7.2,
    voteCount: 500,
    popularity: 25.1,
    runtime: 167,
    genre: "Drama",
    trailer: "https://www.youtube.com/watch?v=Qz1G4x5q0c0",
    cost: 0,
  },
];

export const mockSubscriptionPlans = [
  {
    id: "plan_basic",
    name: "Basic",
    price: 99,
    currency: "INR",
    duration: "1 month",
    features: [
      "HD Streaming",
      "Watch on 1 device",
      "Limited content library",
    ],
  },
  {
    id: "plan_standard",
    name: "Standard",
    price: 199,
    currency: "INR",
    duration: "1 month",
    features: [
      "Full HD Streaming",
      "Watch on 2 devices",
      "Full content library",
      "Download for offline",
    ],
  },
  {
    id: "plan_premium",
    name: "Premium",
    price: 499,
    currency: "INR",
    duration: "3 months",
    features: [
      "4K Ultra HD Streaming",
      "Watch on 4 devices",
      "Full content library",
      "Download for offline",
      "Priority support",
    ],
  },
];

export const mockWatchlist = [
  { tmdbId: 550, mediaType: "movie", title: "Fight Club", posterPath: mockMovies[0].poster },
  { tmdbId: 1396, mediaType: "tv", title: "Breaking Bad", posterPath: mockShows[0].poster },
  { tmdbId: 155, mediaType: "movie", title: "The Dark Knight", posterPath: mockMovies[4].poster },
];

export const mockNotifications = [
  { id: 1, title: "New Arrival", message: "RRR is now streaming!", read: false, createdAt: "2024-01-15T10:00:00Z" },
  { id: 2, title: "Subscription Reminder", message: "Your subscription expires in 3 days", read: false, createdAt: "2024-01-14T08:00:00Z" },
  { id: 3, title: "Weekend Picks", message: "Check out our top picks for this weekend", read: true, createdAt: "2024-01-12T12:00:00Z" },
];

// ─── Admin Mock Data ───────────────────────────────

export const mockAdminUser = {
  id: 100,
  name: "Admin User",
  email: "admin@cnio.dev",
  imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=admin",
  isSubscribed: true,
  roles: ["ROLE_ADMIN"],
  phone: "+91 9876543210",
  createdAt: "2024-01-01T00:00:00Z",
};

export const mockContentManagerUser = {
  id: 200,
  name: "Content Manager",
  email: "cm@cnio.dev",
  imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=cm",
  isSubscribed: false,
  roles: ["ROLE_CONTENT_MANAGER"],
  phone: "+91 9876543211",
  createdAt: "2024-02-01T00:00:00Z",
};

export const mockCustomers = [
  { id: 1, name: "Naren Dev", email: "naren@cnio.dev", phoneNumber: "+91 8072205480", address: "Chennai, India", imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=naren", roles: ["ROLE_USER"], isSubscribed: true, isActive: true, createdAt: "2024-06-15T10:00:00Z", updatedAt: "2024-06-15T10:00:00Z" },
  { id: 2, name: "Priya Kumar", email: "priya@example.com", phoneNumber: "+91 9876543210", address: "Mumbai, India", imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya", roles: ["ROLE_USER"], isSubscribed: false, isActive: true, createdAt: "2024-07-01T10:00:00Z", updatedAt: "2024-07-01T10:00:00Z" },
  { id: 3, name: "Rahul Singh", email: "rahul@example.com", phoneNumber: "+91 9123456789", address: "Delhi, India", imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=rahul", roles: ["ROLE_USER"], isSubscribed: true, isActive: true, createdAt: "2024-07-10T10:00:00Z", updatedAt: "2024-07-10T10:00:00Z" },
  { id: 4, name: "Anita Desai", email: "anita@example.com", phoneNumber: "+91 9988776655", address: "Bangalore, India", imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=anita", roles: ["ROLE_USER"], isSubscribed: false, isActive: false, createdAt: "2024-08-01T10:00:00Z", updatedAt: "2024-08-01T10:00:00Z" },
  { id: 5, name: "Vikram Patel", email: "vikram@example.com", phoneNumber: "+91 9871234567", address: "Pune, India", imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=vikram", roles: ["ROLE_USER"], isSubscribed: true, isActive: true, createdAt: "2024-08-15T10:00:00Z", updatedAt: "2024-08-15T10:00:00Z" },
];

export const mockAdmins = [
  { id: 100, name: "Admin User", email: "admin@cnio.dev", phoneNumber: "+91 9876543210", address: "Chennai, India", imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=admin", roles: [{ name: "ROLE_ADMIN" }], isActive: true, department: "IT", accessLevel: 4, createdAt: "2024-01-01T00:00:00Z", lastLogin: "2024-09-01T10:00:00Z" },
  { id: 101, name: "Super Admin", email: "super@cnio.dev", phoneNumber: "+91 9876543211", address: "Chennai, India", imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=super", roles: [{ name: "ROLE_SUPER_ADMIN" }], isActive: true, department: "Management", accessLevel: 4, createdAt: "2024-01-01T00:00:00Z", lastLogin: "2024-09-01T10:00:00Z" },
];

export const mockContentManagers = [
  { id: 200, name: "Content Manager", email: "cm@cnio.dev", phoneNumber: "+91 9876543211", imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=cm", department: "Content", specialization: "both", accessLevel: 2, isActive: true, createdAt: "2024-02-01T00:00:00Z" },
  { id: 201, name: "Movie Expert", email: "movies@cnio.dev", phoneNumber: "+91 9876543212", imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=moviecm", department: "Movies", specialization: "movies", accessLevel: 1, isActive: true, createdAt: "2024-03-01T00:00:00Z" },
];

export const mockCustomerStats = [
  { month: 1, total: 45 },
  { month: 2, total: 52 },
  { month: 3, total: 61 },
  { month: 4, total: 48 },
  { month: 5, total: 73 },
  { month: 6, total: 89 },
  { month: 7, total: 95 },
  { month: 8, total: 110 },
];
