version: "3.9"

services:
  db:
    container_name: postgres-mv
    image: postgres:17.6
    environment:
      POSTGRES_DB: movieott
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis-mv
    image: redis:7.4
    ports:
      - "6379:6379"
    networks:
      - db
    restart: unless-stopped

  app:
    image: codenaren23/movies-api:latest
    container_name: movie-api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_URL: ${SPRING_DATA_REDIS_URL}
      SUPER_ADMIN_EMAIL: ${SUPER_ADMIN_EMAIL}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}
      BREVO_API_KEY: ${BREVO_API_KEY}
      BREVO_SENDER_EMAIL: ${BREVO_SENDER_EMAIL}
      BREVO_SENDER_NAME: ${BREVO_SENDER_NAME}
      TMDB_API_KEY: ${TMDB_API_KEY}
      DATA_INITIALIZATION_ENABLED: ${DATA_INITIALIZATION_ENABLED}

    networks:
      - db

    restart: unless-stopped

volumes:
  postgres_data:

networks:
  db:
    driver: bridge