-- Create sequences for test database if they don't exist
CREATE SEQUENCE IF NOT EXISTS customer_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS movie_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS show_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS payment_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS subscription_plan_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS role_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS password_reset_token_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS subscription_intent_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS user_plan_info_id START WITH 1 INCREMENT BY 1;
