ALTER TABLE movie
    ADD COLUMN IF NOT EXISTS age_rating VARCHAR(255) NOT NULL DEFAULT 'PG-13';

ALTER TABLE movie
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE movie
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
