ALTER TABLE customer
    ADD COLUMN IF NOT EXISTS image_url VARCHAR (255);

ALTER TABLE customer
    ADD COLUMN IF NOT EXISTS is_email_verified BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE customer
    ADD COLUMN IF NOT EXISTS address TEXT NOT NULL DEFAULT 'None';

ALTER TABLE customer
    ADD COLUMN IF NOT EXISTS is_registered BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE customer
    ADD COLUMN IF NOT EXISTS is_subscribed BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE customer
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP (6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE customer
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP (6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
