-- Add missing columns to show table to align with Show entity
ALTER TABLE show
    ADD COLUMN IF NOT EXISTS age_rating VARCHAR(255) NOT NULL DEFAULT 'PG-13';

ALTER TABLE show
    ADD COLUMN IF NOT EXISTS type VARCHAR(255) NOT NULL DEFAULT 'shows';

ALTER TABLE show
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE show
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
