ALTER TABLE movie
    ADD COLUMN description VARCHAR(255) NOT NULL DEFAULT 'None';

ALTER TABLE movie
    ADD COLUMN poster VARCHAR(255) NOT NULL DEFAULT 'None';

ALTER TABLE movie
    ADD COLUMN year INTEGER NOT NULL DEFAULT 2000;

ALTER TABLE movie
    ADD COLUMN runtime VARCHAR(255) NOT NULL DEFAULT 'None';

ALTER TABLE movie
    ADD COLUMN genre VARCHAR(255) NOT NULL DEFAULT 'None';

ALTER TABLE show
    ADD COLUMN description VARCHAR(255) NOT NULL DEFAULT 'None';

ALTER TABLE show
    ADD COLUMN poster VARCHAR(255) NOT NULL DEFAULT 'None';

ALTER TABLE show
    ADD COLUMN year INTEGER NOT NULL DEFAULT 2000;

ALTER TABLE show
    ADD COLUMN runtime VARCHAR(255) NOT NULL DEFAULT 'None';

ALTER TABLE show
    ADD COLUMN genre VARCHAR(255) NOT NULL DEFAULT 'None';