server:
  error:
    include-message: always
  port: 8080

spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false

logging:
  level:
    org.springframework.security: TRACE
    com.naren.moviesapp: DEBUG

app:
  data-initialization:
    enabled: ${DATA_INITIALIZATION_ENABLED:true}
  superadmin:
    email: ${SUPER_ADMIN_EMAIL:superadmin@movies.com}
    password: ${SUPER_ADMIN_PASSWORD:ChangeMe123!}
  tmdb:
    api-key: ${TMDB_API_KEY:dev}
    base-url: https://api.themoviedb.org/3
    image-base-url: https://image.tmdb.org/t/p
