spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  main:
    web-application-type: servlet

  sendgrid:
    api:
      key: ${SENDGRID_API_KEY}
    from:
      email: ${SENDGRID_FROM_EMAIL}
  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL}
app:
  allowed:
    origins: "https://movies-app-complete-js4w-bx4rq0iry-nd199s-projects.vercel.app"

logging:
  level:
    web: debug
    sql: debug
    org:
      springframework:
        security: debug