server:
  port: 8080
spring:
  mvc:
    static-path-pattern: /**
  datasource:
    url: jdbc:postgresql://localhost:5332/moviebooking
    username: codeNaren
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: codenaren@gmail.com
    password: sugljpuestlecegt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    web: debug
    sql: debug
    org:
      springframework:
        security: debug
