spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: false

  main:
    web-application-type: servlet
    lazy-initialization: true

  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL}

app:
  superadmin:
    email: ${SUPER_ADMIN_EMAIL}
    password: ${SUPER_ADMIN_PASSWORD}
  demo:
    email: demo@example.com
    password: Demo123456

  brevo:
    api-key: ${BREVO_API_KEY}
    sender:
      email: ${BREVO_SENDER_EMAIL}
      name: ${BREVO_SENDER_NAME:MoviesApp}

  data-initialization:
    enabled: ${DATA_INITIALIZATION_ENABLED:true}

  allowed:
    origins: "https://movies-app-complete.vercel.app"

  tmdb:
    api-key: ${TMDB_API_KEY}
    base-url: https://api.themoviedb.org/3
    image-base-url: https://image.tmdb.org/t/p

logging:
  level:
    root: WARN
    com.naren.moviesapp: INFO
    org.springframework.security: WARN
    org.springframework.mail: DEBUG
    jakarta.mail: DEBUG
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN